# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da76aeb9552d2f1425396cbf2cab70d23d7ece214d8a08e1cac6b558a72c1a3201493cfb95821196413e4aacdb943e60652aa97119949f3a865e4ca649f546cf

test:
  secret_key_base: f13848466260c8d53f135837b6e2a59f3b48d6a4fb333c747985d2bfc5a162aff996dfb5cfb132d5b01e0d54354b377ff6ee1e7d4161685268ae4ba692b49a5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
